# This file was generated by GoReleaser. DO NOT EDIT.
cask "sentgraph-mcp" do
  version "0.4.1"

  on_macos do
    on_intel do
      sha256 "19ac462c73079ecb893575c7c8d10395e946de32d43b177fc393aab087b07f23"
      url "https://github.com/shilin23061991/sentgraph-mcp/releases/download/v#{version}/sentgraph-mcp_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "dd49c05f2cc081b86cc732bac080dfdb0f45c35754e31a0941a88b41c59b5e46"
      url "https://github.com/shilin23061991/sentgraph-mcp/releases/download/v#{version}/sentgraph-mcp_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "69a200ac9275a6a2bd8b9893c7e1c32a2c8768cb442f164bad91a4b048f25850"
      url "https://github.com/shilin23061991/sentgraph-mcp/releases/download/v#{version}/sentgraph-mcp_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "e7c6af21a985cc5f79d3e38af29a0ca336240d9ae3b690c5d0cd7a54f25b3482"
      url "https://github.com/shilin23061991/sentgraph-mcp/releases/download/v#{version}/sentgraph-mcp_#{version}_linux_arm64.tar.gz"
    end
  end

  name "sentgraph-mcp"
  desc "Zep Cloud-backed long-term memory MCP server for coding agents."
  homepage "https://github.com/shilin23061991/sentgraph-mcp"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "sentgraph-mcp"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/sentgraph-mcp"]
    end
  end

  # No zap stanza required

end
