# This file was generated by GoReleaser. DO NOT EDIT.
cask "sentgraph-mcp" do
  version "0.5.0"

  on_macos do
    on_intel do
      sha256 "4647aa5f5ed3117674283a80b36b3677540f93eb2fe0ebf9cdb79fe5df90a64b"
      url "https://github.com/stashilin/sentgraph-mcp/releases/download/v#{version}/sentgraph-mcp_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "2ecd947b0a73863674e97fe22aedece75d9de9b43a1201e1237a5c05e02a7e59"
      url "https://github.com/stashilin/sentgraph-mcp/releases/download/v#{version}/sentgraph-mcp_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "d12422dca206645f473fbd29b5cb9ca468a35e807cdea681f599d4e6cb53b3ab"
      url "https://github.com/stashilin/sentgraph-mcp/releases/download/v#{version}/sentgraph-mcp_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "bb26516759d39dc05cd861d5bf1e8d8bfb6ea500ae3a685e7ee89e8da2f4d314"
      url "https://github.com/stashilin/sentgraph-mcp/releases/download/v#{version}/sentgraph-mcp_#{version}_linux_arm64.tar.gz"
    end
  end

  name "sentgraph-mcp"
  desc "Zep Cloud-backed long-term memory MCP server for coding agents."
  homepage "https://github.com/stashilin/sentgraph-mcp"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "sentgraph-mcp"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/sentgraph-mcp"]
    end
  end

  # No zap stanza required

end
